import type { Metadata } from "next";
import "./globals.css";

import TopNav from "@/components/navigation/TopNav";
import Footer from "@/components/auth/Footer";
import { geistMono, geistSans } from "@/shared/fonts/font";
import { ConfigProvider } from "antd";
import { MAIN_THEME } from "@/shared/colors";
import { AuthProvider } from "@/shared/hooks/useAuthContext";
import { cookies } from "next/headers";
import { decryptJwt } from "@/shared/utils/jwt";
import PageWrapper from "@/components/global/PageWrapper";
import { WebSocketProvider } from "@/shared/hooks/useWebSocketContext";

export const metadata: Metadata = {
  title: "Lorem",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = (await cookies()).get("authToken")?.value
  const authToken = await decryptJwt(cookie)
  const userId = authToken?.id ? (authToken.id as string) : ""
  const isAdmin = authToken?.isAdmin ? (authToken.isAdmin as boolean) : false
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full flex flex-col h-screen overflow-hidden`}
      >
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: MAIN_THEME.primary,
            },
          }}
        >
          <AuthProvider userId={userId} isAdmin={isAdmin}>
            <WebSocketProvider userId={userId}>
              <div className="shrink-0 w-full z-10">
                <TopNav />
              </div>

              <main className="bg-amber-50 w-full flex-1 flex flex-col items-center overflow-y-auto">
                <PageWrapper>
                  {children}
                </PageWrapper>

                <div className="w-full shrink-0 mt-8">
                  <Footer />
                </div>
              </main>
            </WebSocketProvider>
          </AuthProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
