import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import TopNav from "@/components/navigation/TopNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lorem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased w-full flex flex-col 
      h-screen items-center`}>
        <TopNav />
        <main className="flex flex-col bg-amber-50 items-center w-full overflow-y-auto h-screen"
        >
          <div className="w-full bg-white h-full overflow-y-auto">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
